[tool.mypy]
ignore_missing_imports = true
disallow_untyped_defs = true
show_error_codes = true
no_implicit_optional = true
warn_return_any = true
warn_unused_ignores = true

[tool.pylint]
disable = ["C0301", "R0914", "I1101", "R1705", "R0915", "R0902", "W1203", "R0801", "R0913"]