# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python library

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:

    name: Build ${{ matrix.archs }} wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            archs: "x86_64, i686"
          - os: windows-latest
            archs: "x86"
          - os: macos-latest
            archs: "x86_64, arm64"

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mypy black pytest pylint
    - name: Install library
      run: |
        pip install .
    - name: Lint with mypy
      run: |
        mypy **/*.py
    - name: Lint with black
      run: |
        black --check **/*.py
    - name: Lint with pylint
      run: |
        pylint cbpickaxe/*.py cbpickaxe_scripts/*.py
    - name: Run regression tests
      run: |
        make regression_test
